# Workflow Name: Build and Test Prevonto App
name: Build and Test

# Trigger this workflow on push or pull requests to the repository
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: macos-latest  # macOS is required for Xcode builds

    steps:
      # Step 1: Set up XCode (16.x)
      - name: Setup Xcode (16.x)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'  # Uses the highest available 16.x version

      # Step 2: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v4